name: Generate Weave Reference Documentation

on:
  workflow_dispatch:
    inputs:
      weave_version:
        description: 'Weave version (e.g., "latest", "0.51.34", "v0.51.34", commit SHA, or branch name)'
        required: false
        default: 'latest'
        type: string

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('scripts/reference-generation/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install requests for Service API generation
      run: |
        pip install requests
        
    - name: Set version variable
      id: version
      run: |
        VERSION="${{ github.event.inputs.weave_version }}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Using Weave version: ${VERSION}"
        
        # Generate timestamp
        TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
        echo "Generated at: ${TIMESTAMP}"
        
    - name: Generate Service API Documentation
      run: |
        echo "Generating Service API documentation..."
        python scripts/reference-generation/generate_service_api_spec.py
        
    - name: Generate Python SDK Documentation
      run: |
        echo "Generating Python SDK documentation..."
        VERSION="${{ steps.version.outputs.version }}"
        echo "Using Weave version: ${VERSION}"
        
        # Create isolated environment for Python SDK generation
        python -m venv venv_python
        source venv_python/bin/activate
        pip install requests lazydocs
        python scripts/reference-generation/generate_python_sdk_docs.py "${VERSION:-latest}"
        deactivate
        rm -rf venv_python
        
    - name: Generate TypeScript SDK Documentation  
      run: |
        echo "Generating TypeScript SDK documentation..."
        VERSION="${{ steps.version.outputs.version }}"
        echo "Using Weave version: ${VERSION}"
        
        # Create isolated environment for TypeScript SDK generation
        python -m venv venv_typescript
        source venv_typescript/bin/activate
        python scripts/reference-generation/generate_typescript_sdk_docs.py "${VERSION:-latest}"
        deactivate
        rm -rf venv_typescript
        
    - name: Fix broken links
      run: |
        echo "Fixing broken links in documentation..."
        python scripts/reference-generation/fix_broken_links.py
        
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: Update reference documentation (Weave ${{ steps.version.outputs.version }})"
        title: "[Draft] Update reference documentation (Weave ${{ steps.version.outputs.version }})"
        draft: true
        body: |
          This PR updates the reference documentation for Weave.
          
          **Version**: ${{ steps.version.outputs.version }}
          **Generated on**: ${{ steps.version.outputs.timestamp }}
          
          ### Changes
          - Updated Service API documentation from OpenAPI spec
          - Regenerated Python SDK documentation using lazydocs
          - Regenerated TypeScript SDK documentation using typedoc
          - Fixed internal cross-reference links
          
          ### Notes
          - Documentation generation runs in isolated environments
          - All dependencies are development-only and not included in the repository
          - Please review the changes before merging
        branch: update-reference-docs-${{ github.run_number }}
        delete-branch: true
        labels: |
          documentation
          automated
          weave
    
    - name: Display PR Link
      if: steps.create-pr.outputs.pull-request-number
      run: |
        PR_URL="https://github.com/${{ github.repository }}/pull/${{ steps.create-pr.outputs.pull-request-number }}"
        echo "📝 Draft PR created successfully!"
        echo "🔗 Review the changes at: $PR_URL"
        echo ""
        echo "::notice title=Pull Request Created::A draft PR has been created for review: $PR_URL"
